data = as.data.frame(TRAIN)


trisVars = names(TRAIN)
trisVars = trisVars[grep("^tris_", trisVars)]
trisVars = trisVars[!trisVars %in% c("tris_offer_quantity","tris_total_spend","tris_label","tris_has_bought_brand_company","tris_has_bought_brand_company_category","tris_never_bought_category","tris_offer_value","tris_has_bought_category","tris_has_bought_company","tris_has_bought_brand_category")]


TRAIN[,company_a_sc := (tris_has_bought_company_a - mean(tris_has_bought_company_a)) / sd(tris_has_bought_company_a), by=company]
TRAIN[,company_a_30_sc := (tris_has_bought_company_a_30 - mean(tris_has_bought_company_a_30)) / sd(tris_has_bought_company_a_30), by=company]
TRAIN[,company_a_60_sc := (tris_has_bought_company_a_60 - mean(tris_has_bought_company_a_60)) / sd(tris_has_bought_company_a_60), by=company]
TRAIN[,company_a_90_sc := (tris_has_bought_company_a_90 - mean(tris_has_bought_company_a_90)) / sd(tris_has_bought_company_a_90), by=company]
TRAIN[,company_a_180_sc := (tris_has_bought_company_a_180 - mean(tris_has_bought_company_a_180)) / sd(tris_has_bought_company_a_180), by=company]
TRAIN[,category_a_sc := (tris_has_bought_category_a - mean(tris_has_bought_category_a)) / sd(tris_has_bought_category_a), by=category]
TRAIN[,category_a_30_sc := (tris_has_bought_category_a_30 - mean(tris_has_bought_category_a_30)) / sd(tris_has_bought_category_a_30), by=category]
TRAIN[,category_a_60_sc := (tris_has_bought_category_a_60 - mean(tris_has_bought_category_a_60)) / sd(tris_has_bought_category_a_60), by=category]
TRAIN[,category_a_90_sc := (tris_has_bought_category_a_90 - mean(tris_has_bought_category_a_90)) / sd(tris_has_bought_category_a_90), by=category]
TRAIN[,category_a_180_sc := (tris_has_bought_category_a_180 - mean(tris_has_bought_category_a_180)) / sd(tris_has_bought_category_a_180), by=category]
TRAIN[,brand_a_sc := (tris_has_bought_brand_a - mean(tris_has_bought_brand_a)) / sd(tris_has_bought_brand_a), by=brand]
TRAIN[,brand_a_30_sc := (tris_has_bought_brand_a_30 - mean(tris_has_bought_brand_a_30)) / sd(tris_has_bought_brand_a_30), by=brand]
TRAIN[,brand_a_60_sc := (tris_has_bought_brand_a_60 - mean(tris_has_bought_brand_a_60)) / sd(tris_has_bought_brand_a_60), by=brand]
TRAIN[,brand_a_90_sc := (tris_has_bought_brand_a_90 - mean(tris_has_bought_brand_a_90)) / sd(tris_has_bought_brand_a_90), by=brand]
TRAIN[,brand_a_180_sc := (tris_has_bought_brand_a_180 - mean(tris_has_bought_brand_a_180)) / sd(tris_has_bought_brand_a_180), by=brand]
TRAIN[,company_q_sc := (tris_has_bought_company_q - mean(tris_has_bought_company_q)) / sd(tris_has_bought_company_q), by=company]
TRAIN[,company_q_30_sc := (tris_has_bought_company_q_30 - mean(tris_has_bought_company_q_30)) / sd(tris_has_bought_company_q_30), by=company]
TRAIN[,company_q_60_sc := (tris_has_bought_company_q_60 - mean(tris_has_bought_company_q_60)) / sd(tris_has_bought_company_q_60), by=company]
TRAIN[,company_q_90_sc := (tris_has_bought_company_q_90 - mean(tris_has_bought_company_q_90)) / sd(tris_has_bought_company_q_90), by=company]
TRAIN[,company_q_180_sc := (tris_has_bought_company_q_180 - mean(tris_has_bought_company_q_180)) / sd(tris_has_bought_company_q_180), by=company]
TRAIN[,category_q_sc := (tris_has_bought_category_q - mean(tris_has_bought_category_q)) / sd(tris_has_bought_category_q), by=category]
TRAIN[,category_q_30_sc := (tris_has_bought_category_q_30 - mean(tris_has_bought_category_q_30)) / sd(tris_has_bought_category_q_30), by=category]
TRAIN[,category_q_60_sc := (tris_has_bought_category_q_60 - mean(tris_has_bought_category_q_60)) / sd(tris_has_bought_category_q_60), by=category]
TRAIN[,category_q_90_sc := (tris_has_bought_category_q_90 - mean(tris_has_bought_category_q_90)) / sd(tris_has_bought_category_q_90), by=category]
TRAIN[,category_q_180_sc := (tris_has_bought_category_q_180 - mean(tris_has_bought_category_q_180)) / sd(tris_has_bought_category_q_180), by=category]
TRAIN[,brand_q_sc := (tris_has_bought_brand_q - mean(tris_has_bought_brand_q)) / sd(tris_has_bought_brand_q), by=brand]
TRAIN[,brand_q_30_sc := (tris_has_bought_brand_q_30 - mean(tris_has_bought_brand_q_30)) / sd(tris_has_bought_brand_q_30), by=brand]
TRAIN[,brand_q_60_sc := (tris_has_bought_brand_q_60 - mean(tris_has_bought_brand_q_60)) / sd(tris_has_bought_brand_q_60), by=brand]
TRAIN[,brand_q_90_sc := (tris_has_bought_brand_q_90 - mean(tris_has_bought_brand_q_90)) / sd(tris_has_bought_brand_q_90), by=brand]
TRAIN[,brand_q_180_sc := (tris_has_bought_brand_q_180 - mean(tris_has_bought_brand_q_180)) / sd(tris_has_bought_brand_q_180), by=brand]
TRAIN[,company_sc := (tris_has_bought_company - mean(tris_has_bought_company)) / sd(tris_has_bought_company), by=company]
TRAIN[,company_30_sc := (tris_has_bought_company_30 - mean(tris_has_bought_company_30)) / sd(tris_has_bought_company_30), by=company]
TRAIN[,company_60_sc := (tris_has_bought_company_60 - mean(tris_has_bought_company_60)) / sd(tris_has_bought_company_60), by=company]
TRAIN[,company_90_sc := (tris_has_bought_company_90 - mean(tris_has_bought_company_90)) / sd(tris_has_bought_company_90), by=company]
TRAIN[,company_180_sc := (tris_has_bought_company_180 - mean(tris_has_bought_company_180)) / sd(tris_has_bought_company_180), by=company]
TRAIN[,category_sc := (tris_has_bought_category - mean(tris_has_bought_category)) / sd(tris_has_bought_category), by=category]
TRAIN[,category_30_sc := (tris_has_bought_category_30 - mean(tris_has_bought_category_30)) / sd(tris_has_bought_category_30), by=category]
TRAIN[,category_60_sc := (tris_has_bought_category_60 - mean(tris_has_bought_category_60)) / sd(tris_has_bought_category_60), by=category]
TRAIN[,category_90_sc := (tris_has_bought_category_90 - mean(tris_has_bought_category_90)) / sd(tris_has_bought_category_90), by=category]
TRAIN[,category_180_sc := (tris_has_bought_category_180 - mean(tris_has_bought_category_180)) / sd(tris_has_bought_category_180), by=category]
TRAIN[,brand_sc := (tris_has_bought_brand - mean(tris_has_bought_brand)) / sd(tris_has_bought_brand), by=brand]
TRAIN[,brand_30_sc := (tris_has_bought_brand_30 - mean(tris_has_bought_brand_30)) / sd(tris_has_bought_brand_30), by=brand]
TRAIN[,brand_60_sc := (tris_has_bought_brand_60 - mean(tris_has_bought_brand_60)) / sd(tris_has_bought_brand_60), by=brand]
TRAIN[,brand_90_sc := (tris_has_bought_brand_90 - mean(tris_has_bought_brand_90)) / sd(tris_has_bought_brand_90), by=brand]
TRAIN[,brand_180_sc := (tris_has_bought_brand_180 - mean(tris_has_bought_brand_180)) / sd(tris_has_bought_brand_180), by=brand]


TEST[,company_a_sc := (tris_has_bought_company_a - mean(tris_has_bought_company_a)) / sd(tris_has_bought_company_a), by=company]
TEST[,company_a_30_sc := (tris_has_bought_company_a_30 - mean(tris_has_bought_company_a_30)) / sd(tris_has_bought_company_a_30), by=company]
TEST[,company_a_60_sc := (tris_has_bought_company_a_60 - mean(tris_has_bought_company_a_60)) / sd(tris_has_bought_company_a_60), by=company]
TEST[,company_a_90_sc := (tris_has_bought_company_a_90 - mean(tris_has_bought_company_a_90)) / sd(tris_has_bought_company_a_90), by=company]
TEST[,company_a_180_sc := (tris_has_bought_company_a_180 - mean(tris_has_bought_company_a_180)) / sd(tris_has_bought_company_a_180), by=company]
TEST[,category_a_sc := (tris_has_bought_category_a - mean(tris_has_bought_category_a)) / sd(tris_has_bought_category_a), by=category]
TEST[,category_a_30_sc := (tris_has_bought_category_a_30 - mean(tris_has_bought_category_a_30)) / sd(tris_has_bought_category_a_30), by=category]
TEST[,category_a_60_sc := (tris_has_bought_category_a_60 - mean(tris_has_bought_category_a_60)) / sd(tris_has_bought_category_a_60), by=category]
TEST[,category_a_90_sc := (tris_has_bought_category_a_90 - mean(tris_has_bought_category_a_90)) / sd(tris_has_bought_category_a_90), by=category]
TEST[,category_a_180_sc := (tris_has_bought_category_a_180 - mean(tris_has_bought_category_a_180)) / sd(tris_has_bought_category_a_180), by=category]
TEST[,brand_a_sc := (tris_has_bought_brand_a - mean(tris_has_bought_brand_a)) / sd(tris_has_bought_brand_a), by=brand]
TEST[,brand_a_30_sc := (tris_has_bought_brand_a_30 - mean(tris_has_bought_brand_a_30)) / sd(tris_has_bought_brand_a_30), by=brand]
TEST[,brand_a_60_sc := (tris_has_bought_brand_a_60 - mean(tris_has_bought_brand_a_60)) / sd(tris_has_bought_brand_a_60), by=brand]
TEST[,brand_a_90_sc := (tris_has_bought_brand_a_90 - mean(tris_has_bought_brand_a_90)) / sd(tris_has_bought_brand_a_90), by=brand]
TEST[,brand_a_180_sc := (tris_has_bought_brand_a_180 - mean(tris_has_bought_brand_a_180)) / sd(tris_has_bought_brand_a_180), by=brand]
TEST[,company_q_sc := (tris_has_bought_company_q - mean(tris_has_bought_company_q)) / sd(tris_has_bought_company_q), by=company]
TEST[,company_q_30_sc := (tris_has_bought_company_q_30 - mean(tris_has_bought_company_q_30)) / sd(tris_has_bought_company_q_30), by=company]
TEST[,company_q_60_sc := (tris_has_bought_company_q_60 - mean(tris_has_bought_company_q_60)) / sd(tris_has_bought_company_q_60), by=company]
TEST[,company_q_90_sc := (tris_has_bought_company_q_90 - mean(tris_has_bought_company_q_90)) / sd(tris_has_bought_company_q_90), by=company]
TEST[,company_q_180_sc := (tris_has_bought_company_q_180 - mean(tris_has_bought_company_q_180)) / sd(tris_has_bought_company_q_180), by=company]
TEST[,category_q_sc := (tris_has_bought_category_q - mean(tris_has_bought_category_q)) / sd(tris_has_bought_category_q), by=category]
TEST[,category_q_30_sc := (tris_has_bought_category_q_30 - mean(tris_has_bought_category_q_30)) / sd(tris_has_bought_category_q_30), by=category]
TEST[,category_q_60_sc := (tris_has_bought_category_q_60 - mean(tris_has_bought_category_q_60)) / sd(tris_has_bought_category_q_60), by=category]
TEST[,category_q_90_sc := (tris_has_bought_category_q_90 - mean(tris_has_bought_category_q_90)) / sd(tris_has_bought_category_q_90), by=category]
TEST[,category_q_180_sc := (tris_has_bought_category_q_180 - mean(tris_has_bought_category_q_180)) / sd(tris_has_bought_category_q_180), by=category]
TEST[,brand_q_sc := (tris_has_bought_brand_q - mean(tris_has_bought_brand_q)) / sd(tris_has_bought_brand_q), by=brand]
TEST[,brand_q_30_sc := (tris_has_bought_brand_q_30 - mean(tris_has_bought_brand_q_30)) / sd(tris_has_bought_brand_q_30), by=brand]
TEST[,brand_q_60_sc := (tris_has_bought_brand_q_60 - mean(tris_has_bought_brand_q_60)) / sd(tris_has_bought_brand_q_60), by=brand]
TEST[,brand_q_90_sc := (tris_has_bought_brand_q_90 - mean(tris_has_bought_brand_q_90)) / sd(tris_has_bought_brand_q_90), by=brand]
TEST[,brand_q_180_sc := (tris_has_bought_brand_q_180 - mean(tris_has_bought_brand_q_180)) / sd(tris_has_bought_brand_q_180), by=brand]
TEST[,company_sc := (tris_has_bought_company - mean(tris_has_bought_company)) / sd(tris_has_bought_company), by=company]
TEST[,company_30_sc := (tris_has_bought_company_30 - mean(tris_has_bought_company_30)) / sd(tris_has_bought_company_30), by=company]
TEST[,company_60_sc := (tris_has_bought_company_60 - mean(tris_has_bought_company_60)) / sd(tris_has_bought_company_60), by=company]
TEST[,company_90_sc := (tris_has_bought_company_90 - mean(tris_has_bought_company_90)) / sd(tris_has_bought_company_90), by=company]
TEST[,company_180_sc := (tris_has_bought_company_180 - mean(tris_has_bought_company_180)) / sd(tris_has_bought_company_180), by=company]
TEST[,category_sc := (tris_has_bought_category - mean(tris_has_bought_category)) / sd(tris_has_bought_category), by=category]
TEST[,category_30_sc := (tris_has_bought_category_30 - mean(tris_has_bought_category_30)) / sd(tris_has_bought_category_30), by=category]
TEST[,category_60_sc := (tris_has_bought_category_60 - mean(tris_has_bought_category_60)) / sd(tris_has_bought_category_60), by=category]
TEST[,category_90_sc := (tris_has_bought_category_90 - mean(tris_has_bought_category_90)) / sd(tris_has_bought_category_90), by=category]
TEST[,category_180_sc := (tris_has_bought_category_180 - mean(tris_has_bought_category_180)) / sd(tris_has_bought_category_180), by=category]
TEST[,brand_sc := (tris_has_bought_brand - mean(tris_has_bought_brand)) / sd(tris_has_bought_brand), by=brand]
TEST[,brand_30_sc := (tris_has_bought_brand_30 - mean(tris_has_bought_brand_30)) / sd(tris_has_bought_brand_30), by=brand]
TEST[,brand_60_sc := (tris_has_bought_brand_60 - mean(tris_has_bought_brand_60)) / sd(tris_has_bought_brand_60), by=brand]
TEST[,brand_90_sc := (tris_has_bought_brand_90 - mean(tris_has_bought_brand_90)) / sd(tris_has_bought_brand_90), by=brand]
TEST[,brand_180_sc := (tris_has_bought_brand_180 - mean(tris_has_bought_brand_180)) / sd(tris_has_bought_brand_180), by=brand]



